/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestaoclinicafono.grafica;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Date;
import java.sql.Time;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deboravieira
 */
public class Agendamentos extends javax.swing.JFrame {

        private final String CONN_STRING = "jdbc:mysql://localhost:3306/CliniFono?useLegacyDatetimeCode=false&serverTimezone=UTC";
        private final String CONN_USER = "root";
        private final String CONN_PASS = "Pipoca123!";
    public Agendamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageAvatar1 = new icon.ImageAvatar();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidserv = new javax.swing.JTextField();
        txtidpac = new javax.swing.JTextField();
        txtidfunc = new javax.swing.JTextField();
        txtrealizado = new javax.swing.JTextField();
        txtdata = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableagenda = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtProcura = new javax.swing.JTextField();
        jtime = new com.github.lgooddatepicker.components.TimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamentos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar:");

        jLabel3.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id Serviço:");

        jLabel4.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id Paciente:");

        jLabel5.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Id Funcionário:");

        jLabel6.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Realizado?(S/N)");

        jLabel7.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data:");

        tableagenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableagenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableagendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableagenda);

        btnNovo.setBackground(new java.awt.Color(0, 102, 102));
        btnNovo.setFont(new java.awt.Font("PT Serif Caption", 0, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(0, 102, 102));
        btnAlterar.setFont(new java.awt.Font("PT Serif Caption", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 102, 102));
        btnDelete.setFont(new java.awt.Font("PT Serif Caption", 0, 14)); // NOI18N
        btnDelete.setText("Apagar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Horário:");

        txtProcura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProcuraKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtidpac, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtidserv, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtidfunc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtrealizado, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProcura, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel6, txtidfunc, txtidpac, txtidserv, txtrealizado});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtidpac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtidserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtidfunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtrealizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))))))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcura, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void carregaTabela(){
        try{
            Connection SQLCnn = DriverManager.getConnection(CONN_STRING, CONN_USER, CONN_PASS);
            System.out.println("Conectado!");
            Statement st = SQLCnn.createStatement();
            ResultSet res = st.executeQuery("Select * from agendamentos;");
            res.last();
            int row= res.getRow();
            int col= res.getMetaData().getColumnCount();
            res.beforeFirst();
            String rowData[][] = new String[row][col];
            int r = 0;
            while(res.next()){
                for(int i = 0;i<col;i++){
                    rowData[r][i] = res.getString(i+1);
                }
                r++;
            }
            String[]columnName = {"Id Agendamento","Data","Horário","Id Paciente","Id Funcionário","Id Serviço","Realizado(S/N)"};
            DefaultTableModel model =(DefaultTableModel)tableagenda.getModel();
            model.setDataVector(rowData,columnName);          
        }catch(SQLException e){
        }
    }
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        Date data = new Date(txtdata.getDate().getTime()); // Obtém a data do JDateChooser e converte para java.sql.Date
        LocalTime hora = jtime.getTime(); // Obtém a hora do JTimePiker e converte para java.sql.Date
        int idpaciente = Integer.parseInt(txtidpac.getText());
        int idfunc = Integer.parseInt(txtidfunc.getText());
        int idservico = Integer.parseInt(txtidserv.getText());
        String realizado = txtrealizado.getText();

        try{ 
            Connection SQLCnn = DriverManager.getConnection(CONN_STRING, CONN_USER, CONN_PASS);
             PreparedStatement stat1 = SQLCnn.prepareStatement("INSERT INTO agendamentos (data, hora, idpaciente, idfunc, idservico, realizado) "
                     + "VALUES (?, ?, ?, ?, ?, ?)"); 

                System.out.println("Conectado!");

                stat1.setDate(1, new java.sql.Date(data.getTime()));
                var horaAdicionada = hora.plusMinutes(60); //ajuste necessário para o componente funcionar corretamente
                stat1.setTime(2, Time.valueOf(horaAdicionada));
                stat1.setInt(3, idpaciente);
                stat1.setInt(4, idfunc);
                stat1.setInt(5, idservico);
                stat1.setString(6, realizado);

                stat1.executeUpdate();

                // Cria um prontuário associado a esse agendamento
                try (Statement stat2 = SQLCnn.createStatement();
                     ResultSet res = stat2.executeQuery("Select idAgendamento from agendamentos order by idAgendamento desc limit 1;")) {
                    res.next();
                    int idAgendamento = res.getInt("idAgendamento");
                    try (PreparedStatement stat3 = SQLCnn.prepareStatement("INSERT INTO prontuarios (idAgendamento, dataevolucao, evolucao) VALUES (?,?,?)")) {
                        stat3.setInt(1, idAgendamento);
                        stat3.setDate(2, new java.sql.Date(System.currentTimeMillis())); // Data atual para a evolução
                        stat3.setString(3, "Prontuário gerado automaticamente para o agendamento."); // Texto padrão para o prontuário
                        stat3.executeUpdate();
                    }
                }
                JOptionPane.showMessageDialog(null, "Agendamento e prontuário inseridos com sucesso!");
        } catch (SQLException e) { 
                JOptionPane.showMessageDialog(null, "Erro ao inserir agendamento: " + e.getMessage());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Erro na conversão de números: " + e.getMessage());
            }

        txtdata.setDate(null);
        jtime.setTimeToNow();
        txtidfunc.setText("");
        txtidpac.setText("");
        txtidserv.setText("");
        txtrealizado.setText("");
        carregaTabela();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
    
    if (tableagenda.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(null, "Selecione um agendamento para alterar.");
            return;
    }
    
    if (txtdata.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Por favor, selecione uma data.");
            return;
    }
    
    int idAgendamento = Integer.parseInt(tableagenda.getValueAt(tableagenda.getSelectedRow(), 0).toString());
        try{
            Connection SQLCnn = DriverManager.getConnection(CONN_STRING, CONN_USER, CONN_PASS);
             PreparedStatement stat = SQLCnn.prepareStatement("UPDATE agendamentos SET data = ?, hora = ?, idpaciente = ?, idfunc = ?, idservico = ?, realizado = ? "
                     + "WHERE idAgendamento = ?");

            stat.setDate(1, new java.sql.Date(txtdata.getDate().getTime())); // Data
            stat.setTime(2, Time.valueOf(jtime.getTime().plusMinutes(60))); //ajuste necessário para o componente TimePicker funcionar corretamente
            stat.setInt(3, Integer.parseInt(txtidpac.getText())); // ID do paciente
            stat.setInt(4, Integer.parseInt(txtidfunc.getText())); // ID do funcionário
            stat.setInt(5, Integer.parseInt(txtidserv.getText())); // ID do serviço
            stat.setString(6, txtrealizado.getText()); // Realizado
            stat.setInt(7, idAgendamento); // ID do agendamento
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Agendamento alterado com sucesso!");
        }catch (SQLException e) { 
 
            JOptionPane.showMessageDialog(null, "Erro ao alterar agendamento: " + e.getMessage());
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Erro na conversão de números: " + e.getMessage());
        }

        txtdata.setDate(null);
        jtime.setTimeToNow();
        txtidfunc.setText("");
        txtidpac.setText("");
        txtidserv.setText("");
        txtrealizado.setText("");
        carregaTabela();

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        try{
            int id = Integer.parseInt(tableagenda.getValueAt(tableagenda.getSelectedRow(),0).toString());
            Connection SQLCnn = DriverManager.getConnection(CONN_STRING, CONN_USER, CONN_PASS);
            System.out.println("Conectado!");
            Statement st = SQLCnn.createStatement();
            int r = JOptionPane.showConfirmDialog(this,"Essa ação não poderá ser desfeita, tem certeza que quer realizá-la?");
            if(r==0){
            if(!st.execute("Delete from agendamentos where idAgendamento="+id)){
                formWindowOpened(null);
            }
        
            } 
        }catch(HeadlessException | NumberFormatException | SQLException e){
        }
           
            txtdata.setDate(null);
            jtime.setTimeToNow();
            txtidfunc.setText("");
            txtidpac.setText("");
            txtidserv.setText("");
            txtrealizado.setText("");
            carregaTabela();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       carregaTabela();
    }//GEN-LAST:event_formWindowOpened

    private void tableagendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableagendaMouseClicked
          try{
            int id = Integer.parseInt(tableagenda.getValueAt(tableagenda.getSelectedRow(),0).toString());
            Connection SQLCnn = DriverManager.getConnection(CONN_STRING, CONN_USER, CONN_PASS);
            System.out.println("Conectado!");
            Statement st = SQLCnn.createStatement();
            ResultSet res = st.executeQuery("Select * from agendamentos where idAgendamento="+id);
            if(res.next()){
                var horaSubtraida = res.getTime("hora").toLocalTime().minusMinutes(60); //ajuste necessário para o componente funcionar corretamente
                txtdata.setDate(res.getDate("data"));
                jtime.setTime(horaSubtraida);
                txtidfunc.setText(res.getString("idfunc"));
                txtidpac.setText(res.getString("idpaciente"));
                txtidserv.setText(res.getString("idservico"));
                txtrealizado.setText(res.getString("realizado"));
            }           
        }catch(NumberFormatException | SQLException e){
        }
    }//GEN-LAST:event_tableagendaMouseClicked

    private void txtProcuraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProcuraKeyReleased
         try{
            Connection SQLCnn = DriverManager.getConnection(CONN_STRING, CONN_USER, CONN_PASS);
            System.out.println("Conectado!");
            Statement st = SQLCnn.createStatement();
            ResultSet res = st.executeQuery("select a.idAgendamento,a.data,a.hora,a.idpaciente,a.idfunc,a.idservico,a.realizado from agendamentos as a "
                                             + "inner join funcionarios as f on f.idfunc = a.idfunc where f.nome_func like '%" + txtProcura.getText() + "%'");
            res.last();
            int row= res.getRow();
            int col= res.getMetaData().getColumnCount();
            res.beforeFirst();
            String rowData[][] = new String[row][col];
            int r = 0;
            while(res.next()){
                for(int i = 0;i<col;i++){
                    rowData[r][i] = res.getString(i+1);
                }
                r++;
            }
             String[]columnName = {"Id Agendamento","Data","Horário","Id Paciente","Id Funcionário","Id Serviço","Realizado(S/N)"};
            DefaultTableModel model =(DefaultTableModel)tableagenda.getModel();
            model.setDataVector(rowData,columnName);          
        }catch(SQLException e){
        }
    }//GEN-LAST:event_txtProcuraKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agendamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNovo;
    private icon.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.github.lgooddatepicker.components.TimePicker jtime;
    private javax.swing.JTable tableagenda;
    private javax.swing.JTextField txtProcura;
    private com.toedter.calendar.JDateChooser txtdata;
    private javax.swing.JTextField txtidfunc;
    private javax.swing.JTextField txtidpac;
    private javax.swing.JTextField txtidserv;
    private javax.swing.JTextField txtrealizado;
    // End of variables declaration//GEN-END:variables
}
