/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestaoclinicafono.grafica;

/**
 *
 * @author deboravieira
 */
public class Menu1 extends javax.swing.JFrame {

    /**
     * Creates new form Menu1
     */
    public Menu1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicio = new javax.swing.JMenu();
        agenda = new javax.swing.JMenu();
        novoagendamento = new javax.swing.JMenu();
        alteraagenda = new javax.swing.JMenu();
        buscaagenda = new javax.swing.JMenu();
        deletaagenda = new javax.swing.JMenu();
        GPaciente = new javax.swing.JMenu();
        registapac = new javax.swing.JMenu();
        alterapac = new javax.swing.JMenu();
        buscapac = new javax.swing.JMenu();
        deletapac = new javax.swing.JMenu();
        GProfissional = new javax.swing.JMenu();
        registaprof = new javax.swing.JMenu();
        alteraprof = new javax.swing.JMenu();
        buscarprof = new javax.swing.JMenu();
        deletaprof = new javax.swing.JMenu();
        prontuario = new javax.swing.JMenu();
        alterapront = new javax.swing.JMenu();
        buscapront = new javax.swing.JMenu();
        deletapront = new javax.swing.JMenu();
        financeiro = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(59, 171, 171));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N

        inicio.setText("Início");
        jMenuBar1.add(inicio);

        agenda.setText("Agenda");

        novoagendamento.setText("Novo Agendamento");
        novoagendamento.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        agenda.add(novoagendamento);

        alteraagenda.setText("Alterar Agendamento");
        alteraagenda.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        agenda.add(alteraagenda);

        buscaagenda.setText("Buscar Agendamento");
        buscaagenda.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        agenda.add(buscaagenda);

        deletaagenda.setText("Cancelar Agendamento");
        deletaagenda.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        agenda.add(deletaagenda);

        jMenuBar1.add(agenda);

        GPaciente.setText("Gestão de Pacientes");

        registapac.setText("Registo");
        registapac.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        GPaciente.add(registapac);

        alterapac.setText("Alteração");
        alterapac.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        GPaciente.add(alterapac);

        buscapac.setText("Buscar");
        buscapac.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        GPaciente.add(buscapac);

        deletapac.setText("Deletar");
        deletapac.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        GPaciente.add(deletapac);

        jMenuBar1.add(GPaciente);

        GProfissional.setText("Gestão de Profissionais");

        registaprof.setText("Registo");
        registaprof.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        GProfissional.add(registaprof);

        alteraprof.setText("Alteração");
        alteraprof.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        GProfissional.add(alteraprof);

        buscarprof.setText("Buscar");
        buscarprof.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        GProfissional.add(buscarprof);

        deletaprof.setText("Deletar");
        deletaprof.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        GProfissional.add(deletaprof);

        jMenuBar1.add(GProfissional);

        prontuario.setText("Prontuários");

        alterapront.setText("Alteração");
        alterapront.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        prontuario.add(alterapront);

        buscapront.setText("Buscar");
        buscapront.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        prontuario.add(buscapront);

        deletapront.setText("Deletar");
        deletapront.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        prontuario.add(deletapront);

        jMenuBar1.add(prontuario);

        financeiro.setText("Financeiro");
        jMenuBar1.add(financeiro);

        sair.setText("Sair");
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu GPaciente;
    private javax.swing.JMenu GProfissional;
    private javax.swing.JMenu agenda;
    private javax.swing.JMenu alteraagenda;
    private javax.swing.JMenu alterapac;
    private javax.swing.JMenu alteraprof;
    private javax.swing.JMenu alterapront;
    private javax.swing.JMenu buscaagenda;
    private javax.swing.JMenu buscapac;
    private javax.swing.JMenu buscapront;
    private javax.swing.JMenu buscarprof;
    private javax.swing.JMenu deletaagenda;
    private javax.swing.JMenu deletapac;
    private javax.swing.JMenu deletaprof;
    private javax.swing.JMenu deletapront;
    private javax.swing.JMenu financeiro;
    private javax.swing.JMenu inicio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu novoagendamento;
    private javax.swing.JMenu prontuario;
    private javax.swing.JMenu registapac;
    private javax.swing.JMenu registaprof;
    private javax.swing.JMenu sair;
    // End of variables declaration//GEN-END:variables
}
